### ISSUE TITLE
Make widget version configurable

### ISSUE THREAD

**Issue by homm** [smalljoys/meteor-uploadcare#1]
For now, the widget version is hard coded in [ucare.js](https://github.com/smalljoys/meteor-uploadcare/blob/master/ucare.js#L50). Is there any way to make in configurable with a default value? 
It will also be nice to make whole path configurable.

By the way, the latest version is 2.5.9.

**Comment by sgoudie** [comment]
This is a great idea. The default version has been updated in 0.2.0 and we've also allowed an optional setting where developers can set their own widget version.
