### ISSUE TITLE
Move `Meteor.users.update` to separate methods

### ISSUE THREAD

**Issue by homm** [smalljoys/meteor-uploadcare#2]
`addToMediaStorage` and `removeFromMediaStorage ` functions communicate with Uploadcare servers. It is a strange place to update users's model because the files can belong to different models.

It is better to make different methods for storing and update models when future is ready.

**Comment by sgoudie** [comment]
We agree!  I've removed the user storage method from the functions. However, we've also added an optional callback in 0.2.0 that returns the images filesize. A developer can use this in their own user storage methods, to keep track of a user's usage.
